apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: dev-placementrule
  namespace: crd-deploy
spec:
  clusterConditions:
    - type: OK
  clusterSelector:
    matchExpressions: []
    matchLabels:
      environment: Dev
