apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: bookinfo-github
  namespace: bookinfo
  labels:
    app: bookinfo
spec:
  channel: bookinfo/github
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-placementrule
  packageFilter:
    filterRef:
      name: bookinfo-resource-filter-configmap
  timewindow:
    windowtype: "active"
    location: "Europe/Madrid"
    daysofweek: [ "Friday", "Saturday", "Sunday" ]
    hours:
      - start: "05:00PM"
        end: "10:00PM"
