apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: dev-placementrule
  namespace: ansible-demo-sep 
  labels:
    app: ansible-demo
spec:
  clusterSelector:
    matchLabels:
      environment: dev
