apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: patch
  namespace: resource-patch
spec:
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - patch
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
