apiVersion: v1                      
kind: Namespace
metadata:
  name: nginx-objstore-2-ns                             
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: nginx-objstore-2
  namespace: nginx-objstore-2-ns
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - nginx-objstore-2
---
apiVersion: v1                      
kind: Namespace
metadata:
  name: nginx-objstore-2-deva-chn-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: nginx-objstore-2-deva-chn
  namespace: nginx-objstore-2-deva-chn-ns
spec:
  type: ObjectBucket
  pathname: 'http://ec2-100-26-232-156.compute-1.amazonaws.com:9000/deva'
  secretRef:
    name: nginx-objstore-2-objectstore-authentication-0
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-objstore-2-objectstore-authentication-0
  namespace: nginx-objstore-2-deva-chn-ns
data:
  AccessKeyID: YWRtaW4=
  SecretAccessKey: cGFzc3dvcmRhZG1pbg==
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  labels:
    app: nginx-objstore-2
  name: nginx-objstore-2-subscription-0
  namespace: nginx-objstore-2-ns
spec:
  channel: nginx-objstore-2-deva-chn-ns/nginx-objstore-2-deva-chn
  placement:
    placementRef:
      kind: PlacementRule
      name: nginx-objstore-2-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: nginx-objstore-2
  name: nginx-objstore-2-placement
  namespace: nginx-objstore-2-ns
spec:
  clusterReplicas: 3
  clusterSelector:
    matchLabels:
      environment: Dev
