apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: crd-github
  namespace: crd-deploy
  labels:
    app: crd-app
spec:
  channel: crd-deploy/github-crd
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-placementrule
  packageFilter:
    filterRef:
      name: crd-github-cm
