apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: crd-app 
  namespace: crd-deploy
spec:
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - crd-app
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
