apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: configmap-delivery
  namespace: delivery
  labels:
    app: cm-delivery
spec:
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - cm-delivery
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
