apiVersion: v1
kind: Service
metadata:
  name: guestbook-svc
  namespace: guestbook
  labels:
    app: guestbook
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: NodePort
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: guestbook
---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  annotations:
    ian: test-a
  labels:
    tower_job_id: "173"
  name: bigjoblaunch
spec:
  job_template_name: Demo Job Template
  tower_auth_secret: toweraccess
