---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  labels:
    tower_job_id: "173"
  name: posthook-demo-test
  namespace: ansible
spec:
  job_template_name: Demo Post Job
  tower_auth_secret: toweraccess
