apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: bookinfo-github
  namespace: bookinfo
  labels:
    app: bookinfo
spec:
  channel: bookinfo/github
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-placementrule
  packageFilter:
    filterRef:
      name: bookinfo-resource-filter-configmap
  timewindow:
    windowtype: "active"
    location: "America/Toronto"
    hours:
      - start: "09:00AM"
        end: "12:00PM"
      - start: "1:00PM"
        end: "5:40PM"
