apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: ansible
  namespace: ansible-post-only
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - ansible-post-only
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
