---
apiVersion: v1
kind: Namespace
metadata:
  name: delivery
  labels:
    app: cm-delivery
---
apiVersion: v1
kind: Namespace
metadata:
  name: ch-ns
  labels:
    app: cm-delivery
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: cm-delivery-ch
  namespace: delivery
  labels:
    app: cm-delivery
spec:
  type: Namespace
  pathname: delivery
  sourceNamespaces:
    - default
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: ns
  namespace: ch-ns
  labels:
    app: cm-delivery
spec:
  type: Namespace
  pathname: delivery
  sourceNamespaces:
    - default
--- 
apiVersion: apps.open-cluster-management.io/v1
kind: Deployable
metadata: 
  name: payload-cfg-namespace-channel
  annotations: 
    apps.open-cluster-management.io/is-local-deployable: "false"
  namespace: default
spec: 
  channels: 
  - cm-delivery-ch
  - ns
  template: 
    apiVersion: v1
    data: 
      database: mongodb
    kind: ConfigMap
    metadata: 
      name: cfg-from-ch-qa
