---
# Create Subscription for the Helo resource
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: nginx
  namespace: ns-sub-1
  labels:
    app: nginx-app-details
spec:
  channel: ns-ch/predev-ch
  name: nginx-ingress
  packageFilter:
    version: "1.20.x"
  placement:
    placementRef:
      kind: PlacementRule
      name: towhichcluster
