apiVersion: v1
kind: ConfigMap
metadata:
        #  annotations:
        #    github-path: izhang
  name: guestbook-cfgmap
  namespace: guestbook
  labels:
    app: guestbook
spec:
  data: 
    database: mongodb
