apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    github-path: ianzhang
    github-path-2: ianzhang
  name: guestbook-cfgmap
  namespace: guestbook
  labels:
    app: guestbook
spec:
  data: 
    database: mongodb
