apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: ansible-hook
  namespace: ansible-pre-post
  labels:
    app: ansible
  annotations:
    apps.open-cluster-management.io/github-path: git-ops/ansible/appsub-with-pre-post/resources
    apps.open-cluster-management.io/github-branch: e2e
spec:
  channel: ansible-pre-post/git
  hooksecretref:
    name: ansible-tower-secret
    namespace: ansible-pre-post
  placement:
    placementRef:
      kind: PlacementRule
      name: non-local-cluster
