---
apiVersion: v1
kind: Namespace
metadata:
  name: delivery
  labels:
    app: cm-delivery
---
apiVersion: v1
kind: Namespace
metadata:
  name: delivery-sub
  labels:
    app: cm-delivery
---
apiVersion: v1
kind: Namespace
metadata:
  name: ch-ns
  labels:
    app: cm-delivery
