---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: ns-sub
  namespace: delivery-sub
  labels:
    app: cm-delivery
spec:
  channel: delivery/cm-delivery-ch
  placement:
    placementRef: 
      name: towhichcluster
      kind: PlacementRule
  timewindow:
    windowtype: "active"
    location: "America/Toronto"
    hours:
      - start: "09:00AM"
        end: "10:10PM"
