apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: bookinfo-github
  namespace: bookinfo
  labels:
    app: bookinfo
  annotations:
    apps.open-cluster-management.io/git-path: mortgagecm
    apps.open-cluster-management.io/git-branch: master
spec:
  channel: bookinfo/github
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-placementrule
      #  timewindow:
      #    windowtype: "active"
      #    location: "America/Edmonton"
      #    hours:
      #      - start: "05:56AM"
      #        end: "05:56PM"
