---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    github-path: "2000"
  name: guestbook-cfgmap
  labels:
    app: guestbook
data: 
  database: mongodb
---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  labels:
    app: guestbook
  name: normal-ansible-job
spec:
  job_template_name: Demo Job Template
  tower_auth_secret: toweraccess
